matrix:
  include:
    - os: linux
      dist: cosmic
    - language: python
      python: 3.7
      install:
        - pip install yapf==0.25.0
      script:
        - yapf --diff --exclude venv/ --exclude .git/ -r .
