matrix:
  include:
# python formatting
    - language: python
      python: 3.5
      install:
        - pip install yapf==0.25.0
      script:
        - yapf --diff --exclude venv/ --exclude .git/ -r .
