# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-02-19T15:23:06-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "28388c4f22d41854b2caa246602dcb13d55ad13e",
 "version": "0+untagged.221.master.g28388c4"
}
'''  # END VERSION_JSON


def get_versions():
  return json.loads(version_json)
